# -*- coding: utf-8 -*-
"""caculadora python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZvm8FHhS0MrsjI4FMcffy_yLH1ayEIw
"""

#calculadora para a atividade
print ("ola seja bem vido a caculadora")
#perguntar numero e operação
numero1 = input("digite o primeiro numero:\n")
numero2 = input("digite o segundo numero:\n")
operacao = input("digite qual operacao voce quer fazer:\n+(adição)\n-(subtração)\n*(multiplicação)\n/(divisão)\n:")
#converter numeros
numero1 = float(numero1)
numero2 = float(numero2)
#operações sendo feitas
if operacao == "+":
  resultado = numero1 + numero2
  # apresentando resultado
  print (f"resultado da conta é\n:{resultado}")
if operacao == "-":
  resultado = numero1 - numero2
  # apresentando resultado
  print (f"resultado da conta é\n:{resultado}")
if operacao == "*":
  resultado = numero1 * numero2
  # apresentando resultado
  print (f"resultado da conta é\n:{resultado}")
if operacao == "/":
  if numero2 == 0: #caso o segundo numero seja 0
    print ("não é possivel dividir por zero")
  else:
    resultado = numero1 / numero2
    # apresentando resultado
    print (f"resultado da conta é\n:{resultado}")